name: Docs Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'preview' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - name: Install mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Cache build output
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
        with:
          path: .cache
          key: docs-preview-${{ hashFiles('zensical.toml', 'docs/**', 'immich/client/generated/**/*.py') }}
      - name: Run build
        run: mise docs:build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Run deploy
        run: mise docs:deploy --token=${{ secrets.VERCEL_TOKEN }}
