name: Docs Production

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - 'zensical.toml'
      - 'docs/**'
      - 'immich/client/generated/**'
      - '.github/workflows/docs-production.yml'
      - 'vercel.json'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - name: Install mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Cache build output
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
        with:
          path: .cache
          key: docs-production-${{ hashFiles('zensical.toml', 'docs/**', 'immich/client/generated/**/*.py') }}
      - name: Run build
        run: vercel build --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Run deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
